api_version = "2025-07"

[[extensions]]
name = "t:name"
handle = "bundle-cart-transform"
type = "function"
uid = "5aba5aca-3794-6182-792a-573aa0da0363f772ce4c"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.transform.run"
  input_query = "src/cart_transform_run.graphql"
  export = "cart-transform-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/"
  details = "/"
