# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "5bdc04f1757df6ba176ffaffcb0f6989"
name = "Custom Bundle"
application_url = "https://pool-disclaimers-hiking-serving.trycloudflare.com"
embedded = true
handle = "custom-bundle-23"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products,write_cart_transforms,write_publications"


[auth]
redirect_urls = ["https://pool-disclaimers-hiking-serving.trycloudflare.com/auth/callback", "https://pool-disclaimers-hiking-serving.trycloudflare.com/auth/shopify/callback", "https://pool-disclaimers-hiking-serving.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
